### ISSUE TITLE
Definitions of the p-value

### ISSUE THREAD

**Issue by jakobschoepe** [opencasestudies/Bloomberg-ocs-rural-and-urban-obesity#3]
In line 1724 (file: index.Rmd), you are stating that "[t]he p in p-value stands for probability - the probability that we would obtain the statistics (for example the t in our student t-tests based on the means of our groups of comparison) just by random chance alone." However, this statement is wrong (Wasserstein & Lazar, 2016). In line 1451, you gave a more accurate definition of p-values. 

**Reference**
Wasserstein RL, Lazar NA (2016) The ASA Statement on p-values: Context, process, and purpose. Am Stat, 70:129-133

**Comment by carriewright11** [comment]
@jakobschoepe , thank you for pointing this out. We have fixed this.
